/**
 * sapBomEngine.js — SAP BOM Format Generator
 * Satyendra Packaging ERP — Phase 3
 *
 * Converts internal BOM lines into SAP-ready upload format.
 * Output format matches SAP CS01 (BOM Creation) transaction requirements.
 *
 * SAP BOM CSV Columns:
 *  MATNR    — Parent material (Finished Goods code)
 *  WERKS    — Plant
 *  STLAN    — BOM usage (1 = Production)
 *  POSNR    — Item number (0010, 0020...)
 *  POSTP    — Item category (L = Stock, R = Variable)
 *  IDNRK    — Component SAP code
 *  MENGE    — Quantity
 *  MEINS    — UOM
 *  EWAHR    — Item text / description
 */

import { sapMaterials, getSAPCodeByInternal } from '../data/sapMaterials.js';

// SAP system constants
const SAP_PLANT   = 'SPL1';
const SAP_BOM_USE = '1';    // Production BOM
const SAP_STALT   = '1';    // Alternative BOM

/**
 * Generates SAP BOM upload rows from BOM lines.
 * @param {Object} bomHeader      — BOM header info { productCode, productName, quantity }
 * @param {Array}  bomLines       — BomLine[] from bomEngine.js
 * @returns {Array<Object>}       — SAP BOM rows ready for CSV export
 */
export function generateSAPBOM(bomHeader, bomLines) {
  const rows = [];
  const parentSAPCode = getSAPCodeByInternal(bomHeader.productCode) || bomHeader.productCode;

  bomLines.forEach((line, idx) => {
    const posnr     = String((idx + 1) * 10).padStart(4, '0');
    const sapCode   = line.sapCode || getSAPCodeByInternal(line.materialCode) || line.materialCode;
    const itemCat   = line.uom === 'PCS' ? 'R' : 'L';
    const qty       = line.uom === 'PCS'
      ? Math.ceil(line.netRequirement)
      : parseFloat(line.netRequirement.toFixed(4));

    rows.push({
      MATNR:  parentSAPCode,
      WERKS:  SAP_PLANT,
      STLAN:  SAP_BOM_USE,
      STALT:  SAP_STALT,
      POSNR:  posnr,
      POSTP:  itemCat,
      IDNRK:  sapCode,
      MENGE:  qty,
      MEINS:  line.uom,
      EWAHR:  line.description,
      // Extended info (not all SAP uploads need these)
      _category:   line.category,
      _consPerBag: line.consumptionPerBag,
      _wastage:    line.wastagePercent,
      _net:        line.netRequirement,
    });
  });

  return rows;
}

/**
 * Converts SAP BOM rows to CSV string for upload.
 * Only includes columns needed by SAP CS01 batch input.
 * @param {Object}  bomHeader
 * @param {Array}   sapRows       — from generateSAPBOM()
 * @param {boolean} includeHeader — whether to include column headers
 * @returns {string} CSV string
 */
export function exportSAPBOMCSV(bomHeader, sapRows, includeHeader = true) {
  const SAP_COLUMNS = ['MATNR', 'WERKS', 'STLAN', 'STALT', 'POSNR', 'POSTP', 'IDNRK', 'MENGE', 'MEINS', 'EWAHR'];

  const lines = [];

  // Add metadata comment rows (SAP-compatible, start with *)
  lines.push(`* SAP BOM UPLOAD — Generated by Satyendra Packaging ERP`);
  lines.push(`* Product: ${bomHeader.productCode} — ${bomHeader.productName}`);
  lines.push(`* Quantity: ${bomHeader.quantity} PCS`);
  lines.push(`* Date: ${new Date().toLocaleDateString('en-IN')}`);
  lines.push(`* Plant: ${SAP_PLANT}`);
  lines.push('*');

  if (includeHeader) {
    lines.push(SAP_COLUMNS.join(','));
  }

  sapRows.forEach(row => {
    const csvRow = SAP_COLUMNS.map(col => {
      const val = String(row[col] ?? '');
      return val.includes(',') ? `"${val}"` : val;
    });
    lines.push(csvRow.join(','));
  });

  return lines.join('\n');
}

/**
 * Generates an Excel-compatible BOM with full details.
 * Tab-separated for easy paste into Excel.
 * @param {Object} bomHeader
 * @param {Array}  bomLines       — original BomLine[]
 * @param {Array}  sapRows        — from generateSAPBOM()
 * @returns {string} Tab-separated string
 */
export function exportBOMExcel(bomHeader, bomLines, sapRows) {
  const rows = [];

  // Header block
  rows.push(['SATYENDRA PACKAGING LIMITED — BILL OF MATERIALS'].join('\t'));
  rows.push([`BOM Number: ${bomHeader.bomNumber || 'DRAFT'}`, `Date: ${new Date().toLocaleDateString('en-IN')}`].join('\t'));
  rows.push([`Product: ${bomHeader.productCode}`, bomHeader.productName].join('\t'));
  rows.push([`Customer: ${bomHeader.customerName || ''}`, `SO: ${bomHeader.soNumber || ''}`].join('\t'));
  rows.push([`Quantity: ${(bomHeader.quantity || 0).toLocaleString()} PCS`].join('\t'));
  rows.push(['']);

  // Column headers
  rows.push([
    'Seq', 'SAP Code', 'Material Code', 'Description',
    'Category', 'UOM',
    'Cons/Bag (KG)', 'Total Net (KG)', 'Wastage %', 'Wastage Qty', 'Final Req (KG)',
  ].join('\t'));

  // Data rows
  bomLines.forEach(line => {
    rows.push([
      line.seq,
      line.sapCode,
      line.materialCode,
      line.description,
      line.category,
      line.uom,
      line.consumptionPerBag.toFixed(6),
      line.totalConsumption.toFixed(4),
      line.wastagePercent.toFixed(1),
      line.wastageQty.toFixed(4),
      line.netRequirement.toFixed(4),
    ].join('\t'));
  });

  rows.push(['']);

  // Summary
  const totalNet   = bomLines.filter(l => l.uom === 'KG').reduce((s, l) => s + l.totalConsumption, 0);
  const totalGross = bomLines.filter(l => l.uom === 'KG').reduce((s, l) => s + l.netRequirement,   0);
  rows.push(['', '', '', 'TOTAL (KG)', '', '', '', totalNet.toFixed(4), '', '', totalGross.toFixed(4)].join('\t'));

  return rows.join('\n');
}

/**
 * Generates a full BOM summary report as printable HTML string.
 * @param {Object}   bomRecord   — full BOM object from boms.js
 * @param {Array}    bomLines    — BomLine[] array
 * @returns {string} HTML string
 */
export function generateBOMPrintHTML(bomRecord, bomLines) {
  const totalNet   = bomLines.filter(l => l.uom === 'KG').reduce((s, l) => s + l.totalConsumption, 0);
  const totalGross = bomLines.filter(l => l.uom === 'KG').reduce((s, l) => s + l.netRequirement,   0);

  const rowsHTML = bomLines.map(line => `
    <tr>
      <td>${line.seq}</td>
      <td><code>${line.sapCode}</code></td>
      <td>${line.description}</td>
      <td>${line.category}</td>
      <td>${line.uom}</td>
      <td style="text-align:right;">${line.consumptionPerBag.toFixed(6)}</td>
      <td style="text-align:right;">${line.totalConsumption.toFixed(4)}</td>
      <td style="text-align:right;">${line.wastagePercent.toFixed(1)}%</td>
      <td style="text-align:right;">${line.wastageQty.toFixed(4)}</td>
      <td style="text-align:right;font-weight:700;">${line.netRequirement.toFixed(4)}</td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html><html><head>
    <meta charset="UTF-8"/>
    <title>BOM — ${bomRecord.bomNumber || 'DRAFT'}</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: Arial, sans-serif; font-size: 11px; color: #111; padding: 20px; }
      h1 { font-size: 16px; text-align: center; margin-bottom: 4px; }
      h2 { font-size: 12px; background: #0F172A; color: white; padding: 5px 10px; margin: 12px 0 6px; }
      .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 20px; margin-bottom: 12px; border: 1px solid #ddd; padding: 10px; border-radius: 4px; }
      .meta-item { display: flex; gap: 8px; }
      .meta-label { font-weight: 700; color: #555; min-width: 100px; }
      table { width: 100%; border-collapse: collapse; font-size: 10px; }
      th { background: #F1F5F9; padding: 5px 8px; text-align: left; border: 1px solid #ccc; font-size: 10px; }
      td { padding: 4px 8px; border: 1px solid #ddd; vertical-align: middle; }
      tr:nth-child(even) td { background: #FAFAFA; }
      .total-row td { background: #EFF6FF; font-weight: 700; }
      code { font-family: monospace; font-size: 10px; color: #2563EB; }
      .footer { text-align: center; font-size: 9px; color: #999; margin-top: 16px; }
      .badge { padding: 1px 6px; border-radius: 10px; font-size: 9px; background: #ECFDF5; color: #059669; border: 1px solid #A7F3D0; }
      @media print { body { padding: 10px; } }
    </style></head>
    <body>
    <h1>🏭 Satyendra Packaging Limited — Bill of Materials</h1>
    <p style="text-align:center;font-size:10px;color:#666;margin-bottom:12px;">
      Anand, Gujarat | GSTIN: 24AAICS5703P1ZZ | info@satyendragroup.com
    </p>

    <div class="meta-grid">
      <div class="meta-item"><span class="meta-label">BOM Number</span><strong>${bomRecord.bomNumber || 'DRAFT'}</strong></div>
      <div class="meta-item"><span class="meta-label">Date</span>${new Date().toLocaleDateString('en-IN')}</div>
      <div class="meta-item"><span class="meta-label">Product Code</span><code>${bomRecord.productCode}</code></div>
      <div class="meta-item"><span class="meta-label">Product Name</span>${bomRecord.productName}</div>
      <div class="meta-item"><span class="meta-label">Customer</span>${bomRecord.customerName || '—'}</div>
      <div class="meta-item"><span class="meta-label">SO Number</span><code>${bomRecord.soNumber || '—'}</code></div>
      <div class="meta-item"><span class="meta-label">Order Qty</span><strong>${(bomRecord.quantity || 0).toLocaleString()} PCS</strong></div>
      <div class="meta-item"><span class="meta-label">Status</span><span class="badge">${bomRecord.status || 'Draft'}</span></div>
    </div>

    <h2>📋 Material Consumption List</h2>
    <table>
      <thead>
        <tr>
          <th>Seq</th><th>SAP Code</th><th>Description</th><th>Category</th><th>UOM</th>
          <th>Cons/Bag</th><th>Total Net</th><th>Wastage%</th><th>Wastage Qty</th>
          <th>Final Req</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHTML}
        <tr class="total-row">
          <td colspan="6" style="text-align:right;">TOTAL (KG materials only)</td>
          <td style="text-align:right;">${totalNet.toFixed(4)} KG</td>
          <td></td>
          <td></td>
          <td style="text-align:right;">${totalGross.toFixed(4)} KG</td>
        </tr>
      </tbody>
    </table>

    <div class="footer">
      Generated by Satyendra Packaging ERP v3.0 | ${new Date().toLocaleString('en-IN')} | Confidential
    </div>
    <script>window.onload = function() { window.print(); }<\/script>
    </body></html>
  `;
}
